syntax = "proto3";
package numberserver;

service Benchmark {
    rpc IncNum (NumRequest) returns (NumResponse);
    rpc SendVec (VecRequest) returns (VecResponse);
    rpc SendHashmap (HashRequest) returns (HashResponse);
    rpc SetDoneNum (DoneNumRequest) returns (NullResponse);
    rpc SetDoneVec (DoneVecRequest) returns (NullResponse);
    rpc SetDoneHash (DoneHashRequest) returns (NullResponse);
    rpc Barrier (NullResponse) returns (NullResponse);
    rpc ShutDown(NullResponse) returns (NullResponse);  
}

message NumRequest {
}

message NumResponse {
    uint32 number = 1;
}

message VecRequest {
   repeated double vector = 1;
}

message VecResponse{
}

message HashResponse{
}

message HashRequest {
   map<string,string> hashmap = 1;
}

message DoneNumRequest{
    float time_num = 1;
}

message DoneVecRequest{
    float time_vec = 1;
}

message DoneHashRequest{
    float time_hash = 1;
    uint32 hashmap_size = 2;
    uint32 num_nums = 3;
    uint32 num_vecs = 4;
    uint32 num_hash = 5;
    uint32 vec_len = 6;
}

message NullResponse{
}

message ShutDown{
}